<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <PropertyGroup>
  <ApplicationIcon>assets\App.ico</ApplicationIcon>
</PropertyGroup>

<ItemGroup>
  <Content Include="assets\App.ico" />
</ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Installer.Core\Installer.Core.csproj" />
    <ProjectReference Include="..\Installer.Model\Installer.Model.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Assets\brand.sample.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="config.min.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
